Repository FRONTENDSCHOOL8/dream8, pull requests merged in 2024-03, with the labels that each got.

#91 아톰, molecules디자인 분리
  src/components/01_atoms/Exchange/ BeforeLogin.tsx
  src/components/02_molecules/Exchange/User/User.tsx
Labels: feature

#92 [Rename] : 폴더를 atom이 아닌 mocules로 이동(현돈: 15:35)
  src/components/02_molecules/Exchange/Button/BeforeLogin.tsx
Labels: modify

#93 [modify] Header, Footer, SingIn, SignUp 컴포넌트 이동, NewsCard 에러 주석 taewook 18:53
  src/components/01_atoms/Button/Button.tsx
  src/components/01_atoms/Input/Input.tsx
  src/components/02_molecules/SignIn/SignInForm.tsx
  src/components/02_molecules/SignIn/SocialButtonMolecules.tsx
  src/components/02_molecules/SignUp/SignUpInput.tsx
  src/components/03_organisms/Footer/Footer.tsx
  src/components/03_organisms/Footer/ggg
  src/components/03_organisms/Header/GlobalNavBar.tsx
  src/components/03_organisms/Header/Header.tsx
  src/components/03_organisms/Header/gggg
  src/components/03_organisms/Home/NewsCard.tsx
  src/components/03_organisms/SignIn/SocialLoginButtons.tsx
  src/components/04_templates/Exchange/sdf
  src/components/04_templates/Home/HomeContents.tsx
  src/components/04_templates/Login/sdf
  src/components/04_templates/SignIn/SignInTemplates.tsx
  src/components/05_pages/Mypage/MyPage.tsx
  src/components/05_pages/Mypage/MypageUserSetting.tsx
  src/components/05_pages/SignIn/SignIn.tsx
  src/components/05_pages/SignUp/SignUp.tsx
  src/components/Logo/Logo.tsx
  src/components/index.ts
  src/layout/RootLayout.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.stories.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.tsx
  src/pages/Login/SignIn/atoms/SignInFormLogin.stories.tsx
  src/pages/Login/SignIn/atoms/SignInFormLogin.tsx
  src/pages/Login/SignIn/atoms/SocialLoginButton.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginButton.tsx
  src/pages/Login/SignIn/atoms/SocialLoginImage.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginImage.tsx
  src/pages/Login/SignIn/atoms/SocialLoginSpan.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginSpan.tsx
  src/pages/Login/SignIn/molecules/SignInForm.stories.tsx
  src/pages/Login/SignIn/molecules/SocialButtonMolecules.stories.tsx
  src/pages/Login/SignIn/organisms/SocialLoginButtons.stories.tsx
  src/pages/Login/SignIn/templates/SignInTemplates.stories.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
Labels: modify

#95 Feature/product 판매 디테일 페이지 데이터 불러오기
  src/components/02_molecules/Modal/SelectModal/SelectModal.tsx
  src/components/05_pages/Product/ProductDetails/ProductDetails.tsx
Labels: feature

#103 교환 메인 + 작성 + 디테일 페이지 수정
  src/components/01_atoms/StateBox/StateBox.tsx
  src/components/01_atoms/TextArea/TextArea.tsx
  src/components/02_molecules/Exchange/Button/BeforeLogin.tsx
  src/components/02_molecules/Exchange/Button/dfsdf
  src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
  src/components/05_pages/Exchange/Exchange.tsx
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
  src/components/05_pages/Exchange/d.sd
  src/routes/navigation.tsx
  src/store/useListStore.ts
Labels: feature

#104 [Feat] : 로그인한 유저 정보 taewook 19:31
  src/components/02_molecules/SignIn/SignInForm.tsx
  src/components/05_pages/Donation/Donation/Donation.tsx
  src/store/useLoginFormStore.ts
Labels: feature

#106 메인페이지 스크롤
  src/components/01_atoms/News/NewsList/NewsList.tsx
  src/components/03_organisms/Donaion/Donationtable/DonationTable.tsx
  src/components/04_templates/Donation/DonationContent.tsx
  src/components/04_templates/Home/HomeContents.tsx
  src/components/05_pages/Home/Home.tsx
  src/components/05_pages/News/News/News.tsx
Labels: feature

#108 news detail 페이지 구성
  src/components/04_templates/Donation/DonationContent.tsx
  src/components/05_pages/News/News/News.tsx
  src/components/05_pages/News/NewsDetails/NewsDetails.tsx
  src/routes/navigation.tsx
Labels: feature

#112 [Feat] : 회원가입,마이페이지,로그인 여부 표시, 마이페이지 수정, 전역상태값 새로고침 수정 태욱16:35
  src/components/02_molecules/Mypage/CategoryMolecules.tsx
  src/components/02_molecules/Mypage/MypageInfoMolecules.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/SignIn/SignInForm.tsx
  src/components/03_organisms/Header/Header.tsx
  src/components/03_organisms/Mypage/MypageOrganisms.tsx
  src/components/03_organisms/SignIn/SocialLoginButtons.tsx
  src/components/04_templates/SignIn/SignInTemplates.tsx
  src/components/05_pages/Donation/Donation/Donation.tsx
  src/store/useLoginFormStore.ts
  src/styles/tailwindcss.css
Labels: feature

#113 [Feat] : 회원탈퇴+전역상태값 계속유지+ 로그아웃 + 주소검색 태욱 23:49
  package-lock.json
  package.json
  src/components/01_atoms/Input/Input.tsx
  src/components/02_molecules/Mypage/MypageInfoMolecules.tsx
  src/components/02_molecules/SignIn/SignInForm.tsx
  src/components/02_molecules/SignUp/SignUpInput.tsx
  src/components/03_organisms/Header/Header.tsx
  src/components/03_organisms/Header/Logout.tsx
  src/store/useLoginFormStore.ts
  src/utils/formatphoneNumber.ts
Labels: feature

#118 페이지 폴더 삭제
  src/pages/ChatScreen/ChatCard.tsx
  src/pages/ChatScreen/ChatList.tsx
  src/pages/ChatScreen/ChatScreen.tsx
  src/pages/ChatScreen/MessageCard.tsx
  src/pages/Exchange/atom/ExchangeLogin.tsx
  src/pages/Exchange/atom/ExchangeLoginText.tsx
  src/pages/Exchange/atom/ExchangeModifyButton.tsx
  src/pages/Exchange/molecules/ExchangeModify.tsx
  src/pages/Exchange/molecules/ExchangeMore.tsx
  src/pages/Exchange/page/Exchange/Exchange.tsx
  src/pages/Exchange/page/ExchangeDetail/ExchangeDetail.tsx
  src/pages/Exchange/page/ExchangeWrite/ExchangeWrite.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
Labels: feature

#122 [Feat] : 2 formatPhoneNumber 수정 , 거래내역, 후원내역 태욱 18:30
  src/components/02_molecules/Mypage/components/TransactionListCard.tsx
  src/utils/formatphoneNumber.ts
Labels: feature

#123 [modify]: 파일 이름 변경 src/utils/formatphoneNumber.ts 태욱
  src/utils/formatphoneNumber.ts
Labels: modify

#124 [Modify] : 코드 변경 '@/utils/formatphoneNumber' 대소문자 태욱
  src/components/02_molecules/Mypage/MypageUserSetting.tsx
Labels: feature

#131 로딩할때 스피너 추가 및 게시글 수정
  package-lock.json
  package.json
  src/components/01_atoms/StateBox/StateBox.tsx
  src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
  src/components/05_pages/Exchange/Exchange.tsx
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeModify.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
  src/components/Loading/Loading.tsx
  src/hooks/useGetList.ts
  src/hooks/useGetOneUser.ts
  src/layout/RootLayout.tsx
  src/routes/navigation.tsx
Labels: feature

#132 news페이지 useQuery, home페이지 newsCard Ui 수정 (서윤 12:11)
  src/components/01_atoms/Home/NewsMoreButton.tsx
  src/components/01_atoms/News/NewsList/NewsList.tsx
  src/components/03_organisms/Home/NewsCard.tsx
  src/components/04_templates/Home/HomeContents.tsx
  src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
  src/components/05_pages/News/News/News.tsx
  src/components/05_pages/News/NewsDetails/NewsDetails.tsx
  src/routes/navigation.tsx
Labels: modify

#133 [Feat] : 마이페이지 내역 + 프로필 이미지 태욱 20:48
  public/gear.svg
  src/components/01_atoms/Image/Image.tsx
  src/components/02_molecules/Mypage/CategoryMolecules.tsx
  src/components/02_molecules/Mypage/MypageExchane.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.stories.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/Mypage/MypageSponsorship.tsx
  src/components/02_molecules/Mypage/MypageTransaction.tsx
  src/components/02_molecules/Mypage/components/TransactionListCard.tsx
  src/components/03_organisms/Header/GlobalNavBar.tsx
  src/components/03_organisms/Mypage/MypageOrganisms.tsx
  src/store/useLoginFormStore.ts
  src/styles/tailwindcss.css
  src/utils/formatphoneNumber.ts
Labels: feature

#134 [Feat] : usePhotoGridLayout훅, mypage tanstack추가(useQuries) 태욱 21:26
  package-lock.json
  src/components/02_molecules/Mypage/CategoryMolecules.tsx
  src/components/02_molecules/Mypage/MypageExchane.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/Mypage/MypageSponsorship.tsx
  src/components/02_molecules/Mypage/MypageTransaction.tsx
  src/components/02_molecules/Mypage/MypageUserSetting.tsx
  src/components/02_molecules/Mypage/components/TransactionListCard.tsx
  src/components/03_organisms/Mypage/MypageOrganisms.tsx
  src/components/05_pages/Mypage/MyPage.tsx
  src/hooks/usePhotoGridLayout.ts
  src/routes/navigation.tsx
  src/routes/routingStart.tsx
  src/utils/formatphoneNumber.ts
Labels: feature

#135 교환 게시글 수정 페이지 구현
  src/components/02_molecules/Exchange/Button/Chat_Modify.tsx
  src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.tsx
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeModify.tsx
  src/components/Loading/Loading.tsx
  src/hooks/useDelete.ts
Labels: feature

#140 gsap 설치, gsap 애니메이션 적용 (Home) 서윤(18:12)
  package-lock.json
  package.json
  src/components/04_templates/Donation/DonationContent.tsx
  src/components/04_templates/Home/HomeContents.tsx
  src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
  src/components/05_pages/News/News/News.tsx
  src/components/05_pages/News/NewsDetails/NewsDetails.tsx
Labels: feature

#145 [Feat] : 장바구니 Payment에 notification DB에 생성 태욱 11:28
  package-lock.json
  src/api/pocketbase.ts
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/Mypage/MypageUserSetting.tsx
  src/components/03_organisms/Header/GlobalNavBar.tsx
  src/components/03_organisms/Header/Notification/NotificationCommon.tsx
  src/components/03_organisms/Header/Notification/components/CommonLayout.tsx
  src/components/03_organisms/SignIn/SocialLoginButtons.tsx
  src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
  src/components/05_pages/Product/Payment/Payment.tsx
  src/features/SnsService/KakaoRedirect.tsx
  src/store/useLoginFormStore.ts
  src/store/useNoticeList.ts
Labels: feature

#147 [Feat] : 일반알림 - 판매, 후원 구현 record type추가 태욱 13:28
  src/components/03_organisms/Header/GlobalNavBar.tsx
  src/components/03_organisms/Header/Notification/NotificationCommon.tsx
  src/components/03_organisms/Header/Notification/components/CommonLayout.tsx
  src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
  src/components/05_pages/Product/Payment/Payment.tsx
Labels: feature

#166 채팅 아직 아쉽게 미구현 현재까지 진행상황
  public/close.svg
  public/send.svg
  src/components/02_molecules/Exchange/Button/Chat_Modify.tsx
  src/components/02_molecules/Exchange/User/User.tsx
  src/components/05_pages/Exchange/Chat/Chat.tsx
  src/components/05_pages/Exchange/Exchange.tsx
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeModify.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
  src/components/Button/ExchangeWriteButton.tsx
  src/components/Button/MoreButton.tsx
  src/components/Loading/Loading.tsx
  src/hooks/useChatList.ts
  src/routes/navigation.tsx
  tailwind.config.js
Labels: feature

#172 교환 메인페이지 카드 색상 디자인 수정했습니다
  src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
  src/components/05_pages/Exchange/Chat/Chat.tsx
  src/components/05_pages/Exchange/Exchange.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
Labels: feature

#173 [Modify] : 회원가입후 로그인으로이동, skipToContent a태그유지, 카테고리click시 색깔표시, 알림창고정값, 알림없음표시, 비로그인시 로그인하기 이동추가, 마이페이지 내역 3개 미만일 때 더보기 안보이기 태욱
  src/components/02_molecules/Mypage/CategoryMolecules.tsx
  src/components/02_molecules/Mypage/MypageExchange.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/Mypage/MypageSponsorship.tsx
  src/components/02_molecules/Mypage/MypageTransaction.tsx
  src/components/02_molecules/SignUp/SignUpInput.tsx
  src/components/03_organisms/Header/Notification/NotificationCommon.tsx
  src/components/03_organisms/Header/Notification/components/LoginCheckLayout.tsx
  src/components/03_organisms/Header/Notification/components/NothingNotification.tsx
Labels: modify

#175 [Design] : 교환 메인 페이지 게시글 작성 버튼 수정(현돈: 14:39)
  src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
  src/components/05_pages/Exchange/Exchange.tsx
Labels: feature

#176 Update README.md
  README.md
Labels: documentation

#177 [Design] : 교환 디테일 디자인 수정(현돈: 15:02)
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
Labels: feature

#179 찐막 교환 페이지 수정
  src/components/05_pages/Exchange/ExchangeDetail.tsx
Labels: feature

#180 4차 배포 태욱
  README.md
  public/home-section1.webp
  src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
  src/components/02_molecules/Exchange/User/User.tsx
  src/components/02_molecules/Home/Dots.tsx
  src/components/02_molecules/Mypage/CategoryMolecules.tsx
  src/components/02_molecules/Mypage/MypageExchange.tsx
  src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
  src/components/02_molecules/Mypage/MypageSponsorship.tsx
  src/components/02_molecules/Mypage/MypageTransaction.tsx
  src/components/02_molecules/Mypage/components/TransactionListCard.tsx
  src/components/02_molecules/SignUp/SignUpInput.tsx
  src/components/03_organisms/Footer/Footer.tsx
  src/components/03_organisms/Header/Notification/NotificationCommon.tsx
  src/components/03_organisms/Header/Notification/components/LoginCheckLayout.tsx
  src/components/03_organisms/Header/Notification/components/NothingNotification.tsx
  src/components/03_organisms/ProductDetails/RelativeProducts/RelativeProducts.tsx
  src/components/04_templates/Home/HomeContents.tsx
  src/components/05_pages/Exchange/Chat/Chat.tsx
  src/components/05_pages/Exchange/Exchange.tsx
  src/components/05_pages/Exchange/ExchangeDetail.tsx
  src/components/05_pages/Exchange/ExchangeWrite.tsx
  src/components/05_pages/Mypage/MyPage.tsx
  src/components/05_pages/Product/ProductDetails/ProductDetails.tsx
  src/components/Button/SubmitButton.tsx
  src/styles/tailwindcss.css
Labels: good first issue

#187 Update README.md
  README.md
Labels: documentation

#191 Update README.md
  README.md
Labels: documentation

#192 [Feat] : 로그인, 회원가입 validation 추가 [react-hook-form 라이브러리 사용] 태욱
  package-lock.json
  package.json
  src/components/02_molecules/SignIn/SignInForm.tsx
  src/components/02_molecules/SignUp/SignUpInput.tsx
Labels: feature
