Repository FRONTENDSCHOOL8/dream8, pull requests merged in 2024-02, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation

#9 스캐폴딩 배포 테스트
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/@types/global.d.ts
  src/api/pocketbase.js
  src/app/App.css
  src/app/App.tsx
  src/assets/react.svg
  src/components/index.js
  src/main.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/index.css
  src/styles/tailwindcss.css
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: good first issue

#10 [초기설정] 배포테스트 taewook
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
Labels: feature

#11 [초기설정] 배포 테스트 taewook
  README.md
Labels: feature

#12 [초기설정 ]Featuer/initial test taewook
  README.md
Labels: feature

#36 [feature] 기본 네비게이션 구성 taewook
  src/components/Footer/Footer.tsx
  src/components/Header/GlobalNavBar.tsx
  src/components/Header/Header.tsx
  src/components/SkipToContent/SkipToContent.tsx
  src/layout/RootLayout.tsx
  src/pages/ChatScreen/ChatList.tsx
  src/pages/ChatScreen/ChatScreen.tsx
  src/pages/Donation/Donation.tsx
  src/pages/Exchange/Exchange.tsx
  src/pages/Exchange/ExchangeDetails.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/SignIn.tsx
  src/pages/Login/SignUn.tsx
  src/pages/Login/SignUp.tsx
  src/pages/Mypage/MyPage.tsx
  src/pages/Mypage/MypageUserSetting.tsx
  src/pages/News/News.tsx
  src/pages/Product/Payment.tsx
  src/pages/Product/Product.tsx
  src/pages/Product/ProductDetails.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/navigaition.tsx
  src/routes/routingStart.tsx
Labels: feature

#54 Feat/exchange
  src/components/Header/Header.tsx
  src/main.tsx
  src/routes/navigation.tsx
  src/styles/index.css
  src/styles/normalize.css
  src/styles/tailwindcss.css
Labels: good first issue

#57 [Feat] : src/routes/navigation.tsx lazy 로더 수정 taewook 11:49
  src/routes/navigation.tsx
  src/routes/routingStart.tsx
Labels: feature

#58 [Modify] : 코드 변경src/routes/navigation.tsx News변경 taewook 14:00
  src/routes/navigation.tsx
Labels: feature

#59 [Design] : Footer CSS 등 사용자 UI 디자인 변경 tawook 14:44
  src/components/Footer/Footer.tsx
Labels: feature

#60 Feat/exchange 박스 쉐도우 스타일 생성
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.js
  src/api/pocketbase.ts
  tailwind.config.js
Labels: modify

#68 [Feat] : 헤더,푸터 ui 수정, kakao 로그인 수정중 pnpm.lock 파일 삭제 taewook 18:41
  index.html
  package.json
  pnpm-lock.yaml
  public/facebook-icon.svg
  public/google-icon.svg
  public/kakao-icon.svg
  src/api/SocialKakao.ts
  src/components/Header/GlobalNavBar.tsx
  src/components/Header/Header.tsx
  src/features/SnsService/KakaoRedirect.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/pages/Login/SignIn.tsx
  src/pages/Login/SignIn/page/SignIn.tsx
  src/pages/Login/SignUp/page/SignUp.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
  src/store/useKakaoStore.ts
Labels: feature

#72 교환 메인 페이지/디테일 페이지 다시 수정
  index.html
  package-lock.json
  package.json
  public/Trash.svg
  public/logo.svg
  public/profile.svg
  src/app/App.tsx
  src/components/Button/ChatButton.tsx
  src/components/Button/DeleteButton.tsx
  src/components/Button/ExchangeWriteButton.tsx
  src/components/Button/MoreButton.tsx
  src/components/Card/Card.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/GlobalNavBar.tsx
  src/components/Header/Header.tsx
  src/components/Profile/Profile.tsx
  src/layout/RootLayout.tsx
  src/pages/Exchange/Exchange.tsx
  src/pages/Exchange/ExchangeDetails.tsx
  src/pages/Exchange/atom/ExchangeBox.tsx
  src/pages/Exchange/atom/ExchangeLogin.tsx
  src/pages/Exchange/atom/ExchangeLoginText.tsx
  src/pages/Exchange/atom/ExchangeModifyButton.tsx
  src/pages/Exchange/molecules/ExchangeModify.tsx
  src/pages/Exchange/molecules/ExchangeMore.tsx
  src/pages/Exchange/page/Exchange/Exchange.tsx
  src/pages/Exchange/page/ExchangeDetail/ExchangeDetail.tsx
  src/pages/Exchange/page/ExchangeWrite/ExchangeWrite.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
  src/styles/normalize.css
  src/utils/getPbImage.ts
  tailwind.config.js
  tsconfig.json
Labels: feature

#73 [Feat] : 일반 로그인 (회원가입 아직, sns 미완) taewook 15:10
  public/facebook-icon.svg
  src/api/pocketbase.ts
  src/features/SnsService/KakaoRedirect.tsx
  src/pages/Login/SignIn/atoms/SignInForm.tsx
  src/pages/Login/SignIn/atoms/SocialLoginButton.tsx
  src/pages/Login/SignIn/molecules/SocialLoginButtons.tsx
  src/pages/Login/SignIn/page/SignIn.tsx
  src/routes/navigation.tsx
  src/store/useLoggedInState.ts
  src/store/useLoginFormStore.ts
Labels: feature

#79 [Feat] : 로그인 스토리북 작성중 taewook 13:26
  src/components/Header/Header.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.stories.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.tsx
  src/pages/Login/SignIn/atoms/SignInFormLogin.stories.tsx
  src/pages/Login/SignIn/atoms/SignInFormLogin.tsx
  src/pages/Login/SignIn/atoms/SocialLoginButton.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginButton.tsx
  src/pages/Login/SignIn/atoms/SocialLoginImage.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginImage.tsx
  src/pages/Login/SignIn/atoms/SocialLoginSpan.stories.tsx
  src/pages/Login/SignIn/atoms/SocialLoginSpan.tsx
  src/pages/Login/SignIn/molecules/SignInForm.stories.tsx
  src/pages/Login/SignIn/molecules/SignInForm.tsx
  src/pages/Login/SignIn/molecules/SocialButtonMolecules.stories.tsx
  src/pages/Login/SignIn/molecules/SocialButtonMolecules.tsx
  src/pages/Login/SignIn/organisms/SocialLoginButtons.stories.tsx
  src/pages/Login/SignIn/organisms/SocialLoginButtons.tsx
  src/pages/Login/SignIn/page/SignIn.stories.tsx
  src/pages/Login/SignIn/page/SignIn.tsx
  src/pages/Login/SignIn/templates/SignInTemplates.stories.tsx
  src/pages/Login/SignIn/templates/SignInTemplates.tsx
  src/store/useLoginFormStore.ts
Labels: feature

#82 [Feat] : 교환 메인 페이지 로그인 여부에 따라 수정(현돈: 14:51)
  src/pages/Exchange/page/Exchange/Exchange.tsx
Labels: feature

#83 [Modify] : 디렉토리 전면 수정 taewook 15:13
  src/components/01_atoms/Button/sdf
  src/components/01_atoms/Input/sdf
  src/components/02_molecules/Exchange/Button/dfsdf
  src/components/02_molecules/Exchange/sdf
  src/components/02_molecules/Footer/sdf
  src/components/02_molecules/Header/sdf
  src/components/04_templates/Exchange/sdf
  src/components/04_templates/Login/sdf
  src/components/05_pages/Exchange/d.sd
  src/components/05_pages/Login/SignIn.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.stories.tsx
  src/pages/Login/SignIn/atoms/SignInFormInput.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
Labels: modify

#84 [Modify] : 헤더 푸터 03_organisms에 이동 taewook 15:30
  src/components/03_organisms/Footer/ggg
  src/components/03_organisms/Header/gggg
Labels: modify

#85 [Modify] : Atoms 수정 taewook 15:55
  src/components/01_atoms/Button/Button.tsx
  src/components/01_atoms/Button/sdf
  src/components/01_atoms/Input/Input.tsx
  src/components/01_atoms/Input/sdf
  src/components/Input/InputTextArea.tsx
  src/pages/Login/SignIn/page/SignIn.stories.tsx
Labels: feature

#86 input 수정
  src/components/01_atoms/Input/Input.tsx
  src/components/05_pages/Home/Home.tsx
  src/pages/Home/atoms/HomeContents.tsx
  src/pages/Home/molecules/NewsCard.tsx
  src/pages/index.ts
  src/routes/navigation.tsx
Labels: feature

#88 [Feat] : 이미지 atom으로 분리해서 컴포넌트 생성(현돈: 16:53)
  src/components/01_atoms/Image/Image.tsx
Labels: feature
